### ISSUE TITLE
Slow load of database

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#80] opened 2021-09-05 11:35 UTC
Using latest WCS version:

WCS might take minutes to load on new map start. This started happening after I updated WCS, so maybe I already had a fix in place or a workaround to not have it do this. But I didn't check that anymore, so this issue could've been present previously aswell.

My fault for not backing up the fix or thoroughly testing this major issue.

I will restore a  backup of my server and compare differences, if found and tested I will send a PR over ASAP :)

Proof:
![wcs not ready problem](https://user-images.githubusercontent.com/69318638/132125265-207b1bae-d80d-427d-b0e7-b0c5845b9065.png)

**Comment by ThaPwned** [comment] 2022-02-14 21:06
Should be fixed in b22e21147325c152c1162af4e7ebcfb14e5c5647. Please make a new issue if the issue is still present.

**Closed by ThaPwned** 2022-02-14 21:06 UTC
