### ISSUE TITLE
WCS doesnt work on brand new server - CSGO

### ISSUE THREAD

**Issue by eriksen080499** [ThaPwned/WCS#93] opened 2022-07-23 19:57 UTC
Hi, i am not sure if this is the correct place to ask for help, but here goes.
A friend and i just installed a new CSGO server.
We followed the installation manual as described, but WCS doesnt work at all when using it.
As soon as i type "wcs" ingame server console begins spamming this error:
 
![image](https://user-images.githubusercontent.com/109875107/180620890-91f6cbab-42ff-48a0-b322-4f0ff3ade14a.png)

I have tried removing/uninstalling everything and doing it again, and reinstalling C++ 2010 and 2015 as per instructions from source python, and sourcemod/metamod. Originally we tried with Eventscripts as well, but as that didnt function at all, we tried with just the CSGO server and WCS provided by here.

Any help?

**Comment by Phoross** [comment] 2022-07-23 20:01
I'm having the same issue and my server was working fine yesterday. I think it may be useful to open a issue on the Source.Python repo since the problem is with SP and not the mod per se.

**Comment by Phoross** [comment] 2022-07-24 11:41
TL:DR for the other issues: Use SourceMod 1.10 not 1.11
You can fin it here: [SourceMod 1.10](https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6545-windows.zip)

**Comment by eriksen080499** [comment] 2022-07-24 12:59
I'll test with SourceMod 1.10, thank you!

**Comment by eriksen080499** [comment] 2022-07-24 13:52
wcs menu seems to work now @Phoross thats great!
Do you know if there's any place where i can get more help? it seems the forum has shut down (warcraft-source.com/board)

I am struggling with autoexec'ing my es emulator..
i get this error:
![image](https://user-images.githubusercontent.com/109875107/180650205-c821cbd2-6bd6-4d90-9676-867647b3ef61.png)


My autoexec: (as per the guide i followed)
sp plugin load es_emulator			//Loads the Eventscripts Emulator by Ayuto
sp plugin load wcs 				        //Loads the Warcraft-Source version by ThaPwned
sp plugin load commandsx 			//Loads various custom commands required for some races' skills to work
es_load wcs/tools/wcs_essentials		//Loads the eventscripts part of the WCS essentials
es_load popup					//Loads the Popup Menu features so we can freely make use of menus

**Comment by eriksen080499** [comment] 2022-07-24 13:53
and it has the correct name.
![image](https://user-images.githubusercontent.com/109875107/180650273-bd45d99d-38dc-4c2c-8912-d9b7883d5f42.png)

**Comment by Phoross** [comment] 2022-07-24 14:11
There was a change on the autoexec due to this bug! you should redownload the autoexec from the EventScript repo and it should be fine!
Also there is a Discord server on which you can ask for help, here's the link: https://discord.gg/FXdvUWy3

**Comment by ManifestManah** [comment] 2022-07-24 14:13
Hello  @eriksen080499, 

What is going wrong in your installation is probably caused by the autoexec.cfg.
I just pushed out an update to the file in question earlier today, this update should've been out for a while but apparently it wasn't the case. Anyhow what you want to do is go to your csgo/cfg/ directory and open up the autoexec.cfg and replace what is inside of it with the following content instead:

```
//Loads the Eventscripts Emulator by Ayuto
sp plugin load es_emulator

//Loads the Warcraft-Source version by ThaPwned
sp plugin load wcs

//Loads various custom commands required for some races' skills to work
sp plugin load commandsx

//Loads the eventscripts part of the WCS essentials
es_load wcs/tools/wcs_essentials

//Loads the Popup Menu features so we can freely make use of menus
es_load popup
```

If this solved the problem then let me know. Also you can get help on the Warcraft-Source discord server, if you are not already in it then here is a link to join it😄
- https://discord.com/invite/zYASbKz

**Comment by ThaPwned** [comment] 2022-08-06 22:45
As this has been solved, I'm going to close it. Use SourceMod 1.10 until there's a new stable release.

**Closed by ThaPwned** 2022-08-06 22:45 UTC
